version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapi
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: andprof/ac2_ca:latest
    depends_on:
      - database
    networks:
      - default
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: sapi
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8686:8080"

volumes:
  db-volume:
