spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:papi}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  hikari:
    connection-timeout: 30000  # Tempo de espera para a conex√£o (em milissegundos)
    maximum-pool-size: 5       # Tamanho m√°ximo do pool de conex√µes
    max-lifetime: 1800000      # Tempo m√°ximo de vida para uma conex√£o no pool
    idle-timeout: 600000       # Tempo de inatividade antes de uma conex√£o ser descartada

# üîç Habilitar os endpoints de monitoramento do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# üåê Porta da aplica√ß√£o (mant√©m 8080, pois o Docker mapeia 8686:8080)
server:
  port: 8080
